//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluescreenSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluescreenSimulator.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to continue.
        /// </summary>
        internal static string action_to_continue {
            get {
                return ResourceManager.GetString("action_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue.
        /// </summary>
        internal static string action_to_continue_text {
            get {
                return ResourceManager.GetString("action_to_continue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string background_color {
            get {
                return ResourceManager.GetString("background_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command after complete.
        /// </summary>
        internal static string command_after_complete {
            get {
                return ResourceManager.GetString("command_after_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (in seconds).
        /// </summary>
        internal static string delay {
            get {
                return ResourceManager.GetString("delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoticon.
        /// </summary>
        internal static string emoticon {
            get {
                return ResourceManager.GetString("emoticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        internal static string error_code {
            get {
                return ResourceManager.GetString("error_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRQL_NOT_LESS_OR_EQUAL.
        /// </summary>
        internal static string error_code_text {
            get {
                return ResourceManager.GetString("error_code_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : 0E : 016F : BFF9B3D4.
        /// </summary>
        internal static string error_text {
            get {
                return ResourceManager.GetString("error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used command:.
        /// </summary>
        internal static string exe_creator_command {
            get {
                return ResourceManager.GetString("exe_creator_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        internal static string exe_creator_filename {
            get {
                return ResourceManager.GetString("exe_creator_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE Generator.
        /// </summary>
        internal static string exe_creator_window_title {
            get {
                return ResourceManager.GetString("exe_creator_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color (text).
        /// </summary>
        internal static string foreground_color {
            get {
                return ResourceManager.GetString("foreground_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate EXE/Cmd.
        /// </summary>
        internal static string generate_exe_cmd {
            get {
                return ResourceManager.GetString("generate_exe_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me an error.
        /// </summary>
        internal static string give_error {
            get {
                return ResourceManager.GetString("give_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string header_9x_text {
            get {
                return ResourceManager.GetString("header_9x_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has been detected and windows has been shutdown to prevent damage to your computer..
        /// </summary>
        internal static string header_text {
            get {
                return ResourceManager.GetString("header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide QR code completely.
        /// </summary>
        internal static string hide_qr {
            get {
                return ResourceManager.GetString("hide_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (Line 1).
        /// </summary>
        internal static string information_l1 {
            get {
                return ResourceManager.GetString("information_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. To continue:.
        /// </summary>
        internal static string information_l1_text {
            get {
                return ResourceManager.GetString("information_l1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (Line 2).
        /// </summary>
        internal static string information_l2 {
            get {
                return ResourceManager.GetString("information_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to return to Windows, or.
        /// </summary>
        internal static string information_l2_text {
            get {
                return ResourceManager.GetString("information_l2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        internal static string instructions_dialog_mit {
            get {
                return ResourceManager.GetString("instructions_dialog_mit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project page.
        /// </summary>
        internal static string instructions_dialog_project {
            get {
                return ResourceManager.GetString("instructions_dialog_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program simulates a BSOD without any danger or harm for your PC..
        /// </summary>
        internal static string instructions_dialog_t1 {
            get {
                return ResourceManager.GetString("instructions_dialog_t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is using the MIT-licensed library &apos;NDesk.Options&apos;. |.
        /// </summary>
        internal static string instructions_dialog_t10 {
            get {
                return ResourceManager.GetString("instructions_dialog_t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is using the MIT-licensed library &apos;QRCoder&apos;. |.
        /// </summary>
        internal static string instructions_dialog_t11 {
            get {
                return ResourceManager.GetString("instructions_dialog_t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:.
        /// </summary>
        internal static string instructions_dialog_t2 {
            get {
                return ResourceManager.GetString("instructions_dialog_t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You can use the first fields (up to &quot;Background color&quot;) to change the text on the BSOD.
        ///• In the &quot;Background/Foreground color&quot; fields you can set a background/foreground (text) color (RGB format).
        ///• With &quot;Delay&quot;, you can set a BSOD to trigger after a specified amount of seconds.
        ///• QR code is transparent by default. You can choose to hide it (for Windows 8/8.1 style) or use the original-colored one.
        ///• Click &quot;Give me an error&quot; to trigger the BSOD.
        ///• To leave the BSOD screen, press Alt + F4 or F7.
        ///• If [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string instructions_dialog_t3 {
            get {
                return ResourceManager.GetString("instructions_dialog_t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Unsafe Mode? How to enable it?.
        /// </summary>
        internal static string instructions_dialog_t4 {
            get {
                return ResourceManager.GetString("instructions_dialog_t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Unsafe Mode, you can specify a CMD command which will be run after the BSOD &quot;completes&quot; (e.g. a reboot command).
        ///Because this is potentially dangerous, you have to explicitly enable this by running the program from the command
        ///line with the argument &quot;--enable-unsafe&quot;, like this: BluescreenSimulator --enable-unsafe.
        /// </summary>
        internal static string instructions_dialog_t5 {
            get {
                return ResourceManager.GetString("instructions_dialog_t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluescreen Simulator is open source!.
        /// </summary>
        internal static string instructions_dialog_t6 {
            get {
                return ResourceManager.GetString("instructions_dialog_t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out our Github repository.
        /// </summary>
        internal static string instructions_dialog_t7 {
            get {
                return ResourceManager.GetString("instructions_dialog_t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would be glad if you could subscribe to my channel!.
        /// </summary>
        internal static string instructions_dialog_t8 {
            get {
                return ResourceManager.GetString("instructions_dialog_t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlyTech Videos – YouTube Channel.
        /// </summary>
        internal static string instructions_dialog_t9 {
            get {
                return ResourceManager.GetString("instructions_dialog_t9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press CTRL+ALT+DEL to restart your computer. If you do this, 
        ///you will lose any unsaved information in all open applications..
        /// </summary>
        internal static string instructions_text {
            get {
                return ResourceManager.GetString("instructions_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Text (Line 1).
        /// </summary>
        internal static string main_text_l1 {
            get {
                return ResourceManager.GetString("main_text_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC ran into a problem and needs to restart. We&apos;re just.
        /// </summary>
        internal static string main_text_l1_text {
            get {
                return ResourceManager.GetString("main_text_l1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Text (Line 2).
        /// </summary>
        internal static string main_text_l2 {
            get {
                return ResourceManager.GetString("main_text_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collecting some error info, and then we&apos;ll restart for you..
        /// </summary>
        internal static string main_text_l2_text {
            get {
                return ResourceManager.GetString("main_text_l2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string more_info {
            get {
                return ResourceManager.GetString("more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information about this issue and possible fixes, visit https://www.windows.com/stopcode.
        /// </summary>
        internal static string more_info_text {
            get {
                return ResourceManager.GetString("more_info_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color....
        /// </summary>
        internal static string pick_color {
            get {
                return ResourceManager.GetString("pick_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress indicator.
        /// </summary>
        internal static string progress_indicator {
            get {
                return ResourceManager.GetString("progress_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string progress_indicator_text {
            get {
                return ResourceManager.GetString("progress_indicator_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        internal static string rainbow {
            get {
                return ResourceManager.GetString("rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset fields.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting progress.
        /// </summary>
        internal static string starting_process {
            get {
                return ResourceManager.GetString("starting_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps header.
        /// </summary>
        internal static string steps_header {
            get {
                return ResourceManager.GetString("steps_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is the first time you&apos;ve seen this error screen, restart your computer. if this screen appears again. follow these steps:.
        /// </summary>
        internal static string steps_header_text {
            get {
                return ResourceManager.GetString("steps_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to follow.
        /// </summary>
        internal static string steps_to_follow {
            get {
                return ResourceManager.GetString("steps_to_follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to make sure any hardware or software is properly installed.
        ///If this is a new installation. ask your hardware or software manufacturer for any windows updates you might need.
        ///
        ///If problems continue, disable or remove any newly installed hardware or software. Disable BIOS memory options such as caching or shadowing. If you need to use Safe Mode to remove or disable components, restart your computer, press F8 to select Advanced Startup Options, and then select Safe Mode..
        /// </summary>
        internal static string steps_to_follow_text {
            get {
                return ResourceManager.GetString("steps_to_follow_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop code.
        /// </summary>
        internal static string stop_code {
            get {
                return ResourceManager.GetString("stop_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop code: DRIVER_IRQL_NOT_LESS_OR_EQUAL.
        /// </summary>
        internal static string stop_code_text {
            get {
                return ResourceManager.GetString("stop_code_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Person.
        /// </summary>
        internal static string support_person {
            get {
                return ResourceManager.GetString("support_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you call a support person, give them this info:.
        /// </summary>
        internal static string support_person_text {
            get {
                return ResourceManager.GetString("support_person_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original blue QR code.
        /// </summary>
        internal static string use_orig_blue_qr {
            get {
                return ResourceManager.GetString("use_orig_blue_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 Style.
        /// </summary>
        internal static string windows_10_style {
            get {
                return ResourceManager.GetString("windows_10_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 7 Style.
        /// </summary>
        internal static string windows_7_style {
            get {
                return ResourceManager.GetString("windows_7_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 9x Style.
        /// </summary>
        internal static string windows_9x_style {
            get {
                return ResourceManager.GetString("windows_9x_style", resourceCulture);
            }
        }
    }
}
